import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {newWorkspace,validateWorkspace} from './workspace';
export async function access(request:Request,write=false){const user=await getChatGPTUser();if(!user)throw new HttpError(401,'Sign in to load and save your private workspace.');if(write&&request.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'Use the application to save this change.');if(!env.DB)throw new HttpError(503,'Workspace storage is unavailable. Your edits remain in this tab.');return {db:env.DB,owner:user.userId}}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function failure(e:any){if(!(e instanceof HttpError))console.error('Workspace request failed',e?.message);return Response.json({error:e instanceof HttpError?e.message:'Unable to complete this request. Please try again.'},{status:e instanceof HttpError?e.status:503,headers:{'Cache-Control':'no-store'}})}
export function reply(data:any,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
export async function body(request:Request){const limit=1800000;if(Number(request.headers.get('content-length'))>limit)throw new HttpError(413,'Workspace is too large for this edition.');const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'Provide a JSON request object.');const parts:Uint8Array[]=[];let size=0;while(true){const p=await reader.read();if(p.done)break;size+=p.value.byteLength;if(size>limit){await reader.cancel();throw new HttpError(413,'Workspace is too large for this edition.')}parts.push(p.value)}const bytes=new Uint8Array(size);let offset=0;for(const p of parts){bytes.set(p,offset);offset+=p.byteLength}let data;try{data=JSON.parse(new TextDecoder().decode(bytes))}catch{throw new HttpError(400,'Unable to read the submitted data.')}if(!data||typeof data!=='object'||Array.isArray(data))throw new HttpError(400,'Provide a JSON request object.');return data}
export function checked(w:any){const problems=validateWorkspace(w);if(problems.length)throw new HttpError(422,problems.slice(0,6).join(' · '));return w}
export async function carryReviews(db:D1Database,owner:string,state:any){const saved=await getOrCreate(db,owner),previous=JSON.parse(saved.payload);for(const kind of ['criterionAssessments','taxonomyAssessments','actions','readiness'])for(const record of state.esg[kind]){const old=previous.esg[kind].find((r:any)=>r.id===record.id);if(old?.reviewStamp){record.reviewStamp=old.reviewStamp;record.reviewRecordType=old.reviewRecordType}else{delete record.reviewStamp;delete record.reviewRecordType}}return state}
export async function getOrCreate(db:D1Database,owner:string){await db.prepare('INSERT INTO workspaces (owner_id,revision,payload,updated_at) VALUES (?,0,?,?) ON CONFLICT(owner_id) DO NOTHING').bind(owner,JSON.stringify(newWorkspace()),new Date().toISOString()).run();return await db.prepare('SELECT revision,payload,updated_at FROM workspaces WHERE owner_id=?').bind(owner).first<any>()}
