import fs from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
import * as financial from '../lib/financial.mjs';
import * as emissions from '../lib/emissions.mjs';
import * as esg from '../lib/esg.mjs';
const json=n=>JSON.parse(fs.readFileSync(new URL('../lib/'+n,import.meta.url),'utf8'));
const deps={'./financial.mjs':financial,'./emissions.mjs':emissions,'./esg.mjs':esg,'./esg-reference.json':json('esg-reference.json'),'./emissions-reference.json':json('emissions-reference.json')};
function compile(name){const source=fs.readFileSync(new URL('../lib/'+name+'.ts',import.meta.url),'utf8');const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;const m={exports:{}};new Function('require','module','exports',js)(id=>{if(!(id in deps))throw Error('Unexpected import '+id);return deps[id]},m,m.exports);return m.exports}
const workspace=compile('workspace');deps['./workspace']=workspace;const imports=compile('imports');
const w=workspace.newWorkspace(), f=financial.calculate(w), e=esg.calculateEsg({...deps['./esg-reference.json'],initialData:w.esg},{country:w.country,reportDate:w.inputs.settings.reportDate},w.inputs), m=emissions.calculateEmissions(w.emissions,w.inputs);
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name)},close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('seed accepted',()=>assert.deepEqual(workspace.validateWorkspace(w),[]));
test('financial parity',()=>{close(f.opening.grossLoans,269.7);close(f.reportingECL.total,14.3734897863379);close(f.bank[4].cet1After,64.441625499425);close(f.bank[4].totalRWA,181.212411945205)});
test('ESG parity',()=>{assert.equal(e.summary.esHoldsOrDeclines,4);assert.equal(e.summary.pendingClaims,22);close(e.summary.eligibleOrGreenUSDm,16.12);assert.equal(e.summary.verifiedReadinessControls,4)});
test('emissions parity',()=>{close(m.portfolio.financedS1S2,deps['./emissions-reference.json'].expected.portfolio.financedS1S2);assert.equal(m.portfolio.coverageS1S2,1);assert.equal(m.bank.completeScope1And2LB,1714.24)});
for(const scenario of workspace.SCENARIOS)for(const actionsEnabled of [true,false])test(scenario+' actions '+actionsEnabled,()=>{const r=financial.calculate({...w,scenario,actionsEnabled});assert.equal(r.status,'Ready');for(const b of r.bank){assert.ok(Math.abs(b.balanceDifference)<1e-8);assert.ok(Number.isFinite(b.cet1Ratio))}close(r.reportingECL.total,f.reportingECL.total)});
test('action sensitivity is real',()=>assert.ok(financial.calculate({...w,actionsEnabled:false}).bank[4].cet1Ratio<f.bank[4].cet1Ratio));
test('carbon severity changes forecast',()=>assert.notEqual(financial.calculate({...w,carbonScale:2}).bank[4].profitAfterTax,f.bank[4].profitAfterTax));
test('country does not reprice portfolio',()=>close(financial.calculate({...w,country:'Jordan'}).opening.grossLoans,f.opening.grossLoans));
test('Jordan scheme preview cannot inherit approval',()=>{const r=esg.calculateEsg({...deps['./esg-reference.json'],initialData:w.esg},{country:'Jordan',reportDate:46387,scheme:'Auto'},w.inputs);assert.ok(r.taxonomy.some(x=>x.isSchemePreview));assert.equal(r.summary.eligibleOrGreenUSDm,0)});
for(const [name,change]of Object.entries({missingAction:x=>delete x.actionOverride,nullCriterion:x=>x.esg.criterionAssessments[0]=null,objectName:x=>x.inputs.borrowers[0].name={},usdFx:x=>x.inputs.settings.fxUSDPerUnit.USD=2,negativeTarget:x=>x.inputs.settings.cet1Target=-.1,nullActor:x=>x.esg.actors[0]=null,invalidDate:x=>x.inputs.settings.reportDate=null,negativeScale:x=>x.carbonScale=-1,duplicateId:x=>x.inputs.borrowers[1].id=x.inputs.borrowers[0].id,weightSum:x=>x.inputs.settings.accountingCases[0].weight=.9}))test('reject '+name,()=>{const x=structuredClone(w);change(x);assert.ok(workspace.validateWorkspace(x).length)});
test('valid CSV updates only intended values',()=>{const x=imports.importCsv(w,'id,revenue\nB001,65','borrowers');assert.equal(x.state.inputs.borrowers[0].revenue,65);assert.equal(w.inputs.borrowers[0].revenue,financial.DEFAULT_INPUTS.borrowers[0].revenue);assert.equal(x.changes.length,1)});
test('CSV correctly reads quoted and CRLF',()=>assert.deepEqual(imports.parseCsv('\ufeffid,revenue\r\n"B001","65"\r\n'),[['id','revenue'],['B001','65']]));
for(const bad of ['id,revenue\nB001,"6"5','id,revenue\nB001,','id,revenue\nB001,65\nB001,66','id,revenue\nBAD,65','id,revenue\nB001,65\nB002,no'])test('reject malformed CSV '+bad.slice(-12),()=>assert.throws(()=>imports.importCsv(w,bad,'borrowers')));
test('missing evidence remains a draft gap',()=>{const x=structuredClone(w);x.emissions.entities[0].emissionsEvidence='';assert.deepEqual(workspace.validateWorkspace(x),[]);const r=emissions.calculateEmissions(x.emissions,x.inputs);assert.ok(r.portfolio.coverageS1S2<1)});
test('evidence edit invalidates review',()=>{const x=structuredClone(w);x.esg.criterionAssessments[0].evidenceRefs=['new evidence'];const r=esg.calculateEsg({...deps['./esg-reference.json'],initialData:x.esg},{country:'Egypt',reportDate:46387},x.inputs);assert.equal(r.tests[0].validatedResult,'Pending')});
test('closed alone is not verified closure',()=>{const x=structuredClone(w);x.esg.actions[0].requestedState='Closed';const r=esg.calculateEsg({...deps['./esg-reference.json'],initialData:x.esg},{country:'Egypt',reportDate:46387},x.inputs);assert.notEqual(r.actions[0].decisionState,'Closed')});
test('shared facility edit reaches all engines',()=>{const x=structuredClone(w);x.inputs.facilities[0].drawnLocalm=6;const a=financial.calculate(x),b=emissions.calculateEmissions(x.emissions,x.inputs);close(a.opening.grossLoans,f.opening.grossLoans+1);assert.ok(b.portfolio.financedS1S2>m.portfolio.financedS1S2)});
test('review fingerprints are not regenerated on validation',()=>{const x=structuredClone(w);x.esg.criterionAssessments[0].evidenceRefs=['changed'];const old=x.esg.criterionAssessments[0].reviewStamp;workspace.validateWorkspace(x);assert.equal(x.esg.criterionAssessments[0].reviewStamp,old)});
console.log(JSON.stringify({passed:count,status:'All checks passed'}));
