"use client";
import {exportDocument} from '@/lib/platform';
import {ArrowUpRight,ArrowRight,Search,Info} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {ResponsiveContainer,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,ReferenceLine,BarChart,Bar} from 'recharts';
export const fmt=(n:any,d=2)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'Unavailable';
export const pct=(n:any,d=1)=>typeof n==='number'&&Number.isFinite(n)?fmt(n*100,d)+'%':'Unavailable';
export const shortName=(name:string='')=>name.replace(/^Demo /,'');
export const sum=(rows:any[],key:string)=>rows.reduce((s,r)=>s+(typeof r[key]==='number'?r[key]:0),0);
export function Picker({value,onChange,options,label,disabled=false}:any){return <Select value={String(value)} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map((x:any)=><SelectItem key={typeof x==='string'?x:x.value} value={typeof x==='string'?x:String(x.value)}>{typeof x==='string'?x:x.label}</SelectItem>)}</SelectContent></Select>}
export function Metric({label,value,detail,featured=false,onClick}:any){return <div className={'metric '+(featured?'featured':'')}><span>{label}{onClick?<button className="icon-button" onClick={onClick} aria-label={'Explore '+label}><ArrowUpRight size={17}/></button>:<ArrowUpRight size={16}/>}</span><strong>{value}</strong><small>{detail}</small></div>}
export function Tag({children,tone}:any){const s=String(children);const type=tone||(/Hold|Decline|Fail|Breach|Invalid|Prohibited|Funding required/i.test(s)?'danger':/Ready|Clear|Pass|Verified|Green|Eligible|Within|Approved/i.test(s)?'success':/Pending|Review|Conditions|Missing|Unassessed|Unknown|Open|Expired|Amber|Incomplete|Draft/i.test(s)?'warning':'neutral');return <span className={'tag '+type}>{children??'Unavailable'}</span>}
export function Panel({title,subtitle,action,children,className=''}:any){return <section className={'panel '+className}>{title&&<div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>}
export function DataTable({columns,rows,empty='No records match your selection.',rowKey='id'}:any){return <Table><TableHeader><TableRow>{columns.map((c:any)=><TableHead key={c.key} className={c.numeric?'number':''}>{c.label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.length?rows.map((r:any,i:number)=><TableRow key={r[rowKey]??i}>{columns.map((c:any)=><TableCell key={c.key} className={c.numeric?'number':''}>{c.render?c.render(r):r[c.key]??'—'}</TableCell>)}</TableRow>):<TableRow><TableCell colSpan={columns.length}><div className="empty-state">{empty}</div></TableCell></TableRow>}</TableBody></Table>}
export function CustomerButton({customer,onClick}:any){return <button className="customer-name" onClick={()=>onClick(customer.id)}><span className="avatar">{shortName(customer.name).split(' ').map((s:string)=>s[0]).slice(0,2).join('')}</span><span>{shortName(customer.name)}<small>{customer.id}</small></span></button>}
export function SearchBox({value,onChange,placeholder='Search…',label='Search records'}:any){return <label className="search"><Search size={17}/><input placeholder={placeholder} aria-label={label} value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function Field({label,value,onChange,step='any',min,max,type='number',help}:any){return <label className="field"><span>{label}</span><input type={type} value={value??''} step={step} min={min} max={max} onChange={e=>onChange(type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>{help&&<small>{help}</small>}</label>}
export function Notice({children,tone='info'}:any){return <div className={'notice '+tone}><Info size={17}/><div>{children}</div></div>}
export function Plot({data,series,ratio=false,target,height=270,bar=false,xKey='year'}:any){const f=(v:any)=>ratio?pct(v):fmt(v,1);return <div className="plot-wrap"><div style={{height,minWidth:0,width:'100%'}}><ResponsiveContainer width="100%" height="100%">{bar?<BarChart data={data} margin={{top:15,right:22,left:3,bottom:2}}><CartesianGrid vertical={false} stroke="#e7edf0" strokeDasharray="3 5"/><XAxis dataKey={xKey} tick={{fontSize:12,fill:'#788c98'}} axisLine={false} tickLine={false}/><YAxis tickFormatter={f} tick={{fontSize:12,fill:'#788c98'}} axisLine={false} tickLine={false} width={62}/><Tooltip formatter={(v:any,name:any)=>[f(v),name]} contentStyle={{border:'1px solid #dce6eb',borderRadius:9,fontSize:13}}/>{series.map((s:any)=><Bar key={s.key} dataKey={s.key} name={s.label} fill={s.color} radius={[4,4,0,0]} isAnimationActive={false}/>)}</BarChart>:<LineChart data={data} margin={{top:15,right:22,left:3,bottom:2}}><CartesianGrid vertical={false} stroke="#e7edf0" strokeDasharray="3 5"/><XAxis dataKey={xKey} tick={{fontSize:12,fill:'#788c98'}} axisLine={false} tickLine={false}/><YAxis tickFormatter={f} tick={{fontSize:12,fill:'#788c98'}} axisLine={false} tickLine={false} width={62}/><Tooltip formatter={(v:any,name:any)=>[f(v),name]} contentStyle={{border:'1px solid #dce6eb',borderRadius:9,fontSize:13}}/>{target!=null&&<ReferenceLine y={target} stroke="#c69a51" strokeDasharray="4 4"/>}{series.map((s:any)=><Line key={s.key} dataKey={s.key} name={s.label} stroke={s.color} strokeWidth={s.dash?1.8:2.7} strokeDasharray={s.dash?'5 4':undefined} dot={{r:3,fill:'#fff',strokeWidth:2}} activeDot={{r:5}} isAnimationActive={false}/>)}</LineChart>}</ResponsiveContainer></div><div className="chart-legend">{series.map((s:any)=><span key={s.key}><i style={{background:s.color}}/>{s.label}</span>)}{target!=null&&<span><i style={{background:'#c69a51'}}/>Internal target</span>}</div></div>}
export function LinkButton({children,onClick}:any){return <button className="text-button" onClick={onClick}>{children}<ArrowRight size={16}/></button>}
export function download(name:string,text:string,type='application/json'){void exportDocument(name,text,type)}
export function csv(rows:any[],columns:string[]){const safe=(x:any)=>{let s=x==null?'':String(x);if(/^[=+@\t\r]/.test(s)||(/^\-/.test(s)&&typeof x!=='number'))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};return [columns,...rows.map(r=>columns.map(k=>r[k]))].map(r=>r.map(safe).join(',')).join('\r\n')}
